version: 1.2
workflows:
   - name: "IGVF-single_cell_pipeline"
     subclass: WDL
     primaryDescriptorPath: /single_cell_pipeline.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
         tags:
             - /.*/

   - name: "IGVF-sample_fastqs"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf_sample_fastqs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
         tags:
             - /.*/

   - name: "IGVF-check_inputs"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf_check_inputs_synapse.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
         tags:
             - /.*/
             
   - name: "IGVF-kb_index"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf_kb_index.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
         tags:
             - /.*/
             
   - name: "IGVF-kb_count"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf_rna.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
         tags:
             - /.*/
    
   - name: "IGVF-chromap_index"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf_chromap_index.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
         tags:
             - /.*/

   - name: "IGVF-portal_submit"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf_submit_outputs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - sw-portal-submission
         tags:
             - /.*/